Added payment process
TeslimeeM/HotelAutomation pull request #12
Opened 2022-02-17 10:05 UTC by Teeslii

In this section,

2022-02-17 10:56 UTC, Teeslii commented on Invoice.cs
> +
burada belki direkt tüm objeyi vermesem daha iyi olabilirdi çünkü kullanmıyorum.

tutarın öncesinde şu odada, şu kadar süre kalındı gibi bi' çıktı ekleyebiliriz belki.

2022-02-17 11:32 UTC, Teeslii commented on roomControl.cs
>          }
local'deki dosyamda da RoomControl olarak yazıyor ama hala ayrı iki class'mış gibi değişiklikleri kaydediyor. Neden böyle yaptığını da çözemedim.

2022-02-25 10:07 UTC, zencifil requested changes

2022-02-25 10:07 UTC, zencifil commented on Booking.cs
> +        public float Amount { get; set; }
Para icin float kullanma, precision saglayamazsin. 100 lira dedigin zaman float onu 100.000000001 gibi gosterebilir. `decimal` kullanman lazim butun para degiskenleri icin.

2022-02-25 10:07 UTC, zencifil commented on Card.cs
> +        public int Cvc { get; set; }
Eger bunu int yaparsan 017'yi sana 17 olarak verir. O yuzden bunu string olarak tutman lazim.

2022-02-25 10:07 UTC, zencifil commented on Invoice.cs
> +
Ekleyecegin zaman gonderirsin bu objeyi. Basitten basla her zaman. Neye ihtiyacin varsa onu kullan.

2022-02-25 10:07 UTC, zencifil commented on RoomControlService.cs
> +                string BasePriceQuery = "select BasePrice, CheckIn, CheckOut From Room Join Booking on Room.RoomId = Booking.RoomId where  ((CheckIn <=  @CheckOut) and (CheckOut >= @CheckIn)) and Roo
Price'i decimal yapmayi unutma veritabaninda da.

2022-02-25 10:28 UTC, Teeslii commented on Card.cs
> +        public int Cvc { get; set; }
bunun olabilirliği tamamen çıkmış aklımdan, düzeltiyorum

2022-02-25 12:27 UTC, zencifil commented on Payment.cs
> +           if(card.NameSurname != null && card.NumberCard != null && card.Cvc != null)
String degiskenler icin `string.IsNullOrEmpty()` kullan. Bir de oncesinde trim etmeyi unutma. Boylece bir sey yazmak yerine space'e basip gonderirlerse yakalamis olursun.

2022-02-25 12:46 UTC, Teeslii commented on Payment.cs
> +           if(card.NameSurname != null && card.NumberCard != null && card.Cvc != null)
`string.IsNullOrWhiteSpace()`  kullansam nasıl olur ? @zencifil

2022-02-25 13:09 UTC, zencifil commented on Payment.cs
> +           if(card.NameSurname != null && card.NumberCard != null && card.Cvc != null)
O da empty string kontrolu yapmiyor. "" gonderirsen takilmaz o kontrole.

2022-02-28 11:00 UTC, zencifil commented on Payment.cs
> +                System.Windows.Forms.MessageBox.Show("Your payment transaction has failed.");
Burada message box cikarmak yerine exception throw edip bunu cagirdigin yerde yakalarsan daha iyi olur. Boylece bunu bir api yaptigin zaman yani herhangi bir onyuzu olmadigi zaman hatayi on tarafa duzgun bir sekilde aktarabilirsin.

2022-02-28 14:22 UTC, Teeslii commented on Invoice.cs
> +            }
error bildirimini tamamen mi  message box 'tan kaldırmam gerekir ?

message box haricinde denediğim tüm alternatiflerde syntax error aldım. baktığım birkaç yerde böyle kullanılıyordu. bu yüzden eklendilerimde bir eksik olabileceğini düşünüp ona baktım fakat onunla ilgili de bir şey bulamadım. 
en son olarak bu şekilde ekledim

2022-02-28 15:10 UTC, zencifil commented on Invoice.cs
> +            }
Tamamini degil sadece onyuzde olmayanlari. Payment.cs bir form degil, o yuzden form component'lerinii kullanmaman lazim. Sadece form'larda message box kullan. Onlarda da eger arka taraftan bir exception geliyorsa onun mesajini da dahil etmeye calis.

2022-02-28 15:20 UTC, Teeslii commented on Invoice.cs
> +            }
aa okay anladım,, 
o halde başarılı mesajını da message box dan çıkarır onyüze taşırsam bu kısım tamamlanmış olacak sanırım

2022-02-28 15:38 UTC, zencifil commented on Invoice.cs
> +            }
Evet, herhangi bir exception almazsan arka taraftan, basarili demektir.

2022-02-28 15:48 UTC, Teeslii commented
eklemem veya çıkarmam gereken herhangi bi' şey yok ise PR'i kapatıyım mı ?

2022-02-28 15:50 UTC, zencifil approved these changes

2022-02-28 19:46 UTC, merged